// export { default as 기본 모듈 내보내기 } from '모듈'
export { default as Header } from './Header'
export { default as Indicators } from './Indicators'
export { default as A11yHidden } from './A11yHidden'
export { default as Main } from './Main'
